---
- name: 'openvpn-start'
  systemd:
    name: openvpn@{{ ansible_hostname }}.service
    state: started
    enabled: yes
  tags: ['openvpn']

- name: 'openvpn-restart'
  systemd:
    name: openvpn@{{ ansible_hostname }}.service
    enabled: yes
  tags: ['openvpn']
